# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-03-05 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='教室姓名')),
                ('account', models.CharField(max_length=32, verbose_name='教师账号')),
                ('password', models.CharField(max_length=32, verbose_name='教师密码')),
                ('permissions', models.IntegerField(max_length=2, verbose_name='权限')),
            ],
        ),
    ]
